### PR TITLE
First milestone: Using Bootstrap

### PR DESCRIPTION
**Pull request by kiranitor123**
# Clone of Newsweek

Using bootstrap
flexbox, and custom CSS

Styling header and footer

### CODE REVIEW

**Comment by kiranitor123** [comment]
P.S. I worked alone on this project, I don't have a coding partner

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @kiranitor123 :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] The Newsweek logo in the header should have a link (`a` tag)
* [x] Login and Subscribe have links 
* [x] In mobile, the Login button changes into an icon

#### You omitted the main navigation (menu). See a screenshot of what's expected of you in this milestone.
image

The main navigation (menu)

* [x] Uses a nav tag
* [x] Each option has a link
* [x] It has a form with the search field
* [x] In mobile and table the menu hides, and show a hamburger button


### Make the changes and request another review
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by kiranitor123** [comment]
I need to remove a tag inside the button for this linter error:
The element “a” must not appear as a descendant of the “button” element.

**Review by teekaytech — APPROVED** [review]
## Status: Approved :green_circle: 

### Congratulations @kiranitor123 :tada: 

**This project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:**

**Comment(s)**
- It is better you use the unordered/ordered list tag to display a list of elements (i.e. the navigation menu).
```html
<ul>
  <li>
    <a>World</a>
  </li>
  <li>
    <a>U.S</a>
  </li>
</ul>
etc...
```
You can apply this in your header nav items and the footer items.

**_Again, congratulations, you can now merge to master._**

Do not forget to fill the project completion form.
Good luck with your next milestone :handshake: .

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
