### PR TITLE
Magazine content

### PR DESCRIPTION
**Pull request by kiranitor123**
**Complete the structure of the milestone 3**

- Grab all assets of that part of the page
- Missing CSS for getting better page
- I have to complete the code review of milestone 2
- Lost a lot of time with that

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [x] [MANDATORY] In XL Screen, There should be a margin-left and right just like the [ORIGINAL](https://www.newsweek.com/)
  - [x] [MANDATORY] There should be a small space between three columns.
   Capture12
  - [x] [MANDATORY] In 768px screen, this content is breaking, kindly fix it.
   Capture13
  - [x] [MANDATORY] In 768px screen, this content doesn't look like the [ORIGINAL](https://www.newsweek.com/).
          - clone
            Capture14
          - original
            Capture15
  - [x] [MANDATORY] You overused `!important` in your css, kindly try not to overuse it.
  - [x] [MANDATORY] Everywhere you have item in you code try to use `Article` tag instead of `div`.
  - [x] [MANDATORY] Everywhere you have `img` tag in your code, make sure this attribute `alt=""` is not empty.


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @kiranitor123, great job on this project :muscle: Awesome :+1: Most of the mandatory requirements outlined by the previous TSE have been met :smile: However, I would highlight those that were not met so we can work on improving it. Kindly check the comments below:
- Some of the content is breaking!!! We were notified in the previous review, we made some changes but we did not fully implement it, below is the screenshot
dc
- Also, the newsletter section on a min-width of 768px does not look like the original as pointed out by the previous TSE. A screenshot of both the clone and the original was shown. Let us carefully examine it and work on improving it

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by kiranitor123** [comment]
Screen Shot 2021-03-04 at 15 31 58

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED 🟢 👏 
-------
Hello, there 👋 you did an excellent job working on the required changes. 👏 💪 
There is some things to have in mind 🤔 
-------

- [x] Your last two commits are not imperative. Remember that the commit messages must be in the imperative. [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read about the formatting rules. [Here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read how to change the commit messages. Keep this formating rules in mind for the next commits. 
------------
You can merge this branch now 💯 congrats 🥳 
HAPPY CODING AND GOOS LUCK WITH THE NEXT PROJECTS!!! 

Well-Done-Applause

**Pull request merged**
